config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'users/update'
  
  get 'users/destroy'
  get 'users/index'
  get 'users/show'
  get 'loads/index'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :kaderes
  resources :carriers
  resources :loads
  resources :users
  get 'home/index'
  get 'home/index2'
  get 'home/about'
  get 'home/login'

  get '/search',to: "home#search"

   
  

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/carrier.rb
class Carrier < ApplicationRecord
    has_many :kaderes, dependent: :destroy
       
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :set_carrier, only: %i[ show edit update destroy ]

  # GET /carriers or /carriers.json
  def index
    @carriers = Carrier.all
    @q =Carrier.ransack(params[:q])
    @carriers = @q.result

  end
  # GET /carriers/1 or /carriers/1.json
  def show
  end

  # GET /carriers/new
  def new
    @carrier = Carrier.new
  end

  # GET /carriers/1/edit
  def edit
  end

  # POST /carriers or /carriers.json
  def create
    @carrier = Carrier.new(carrier_params)

    respond_to do |format|
      if @carrier.save
        format.html { redirect_to carrier_url(@carrier), notice: "Carrier was successfully created." }
        format.json { render :show, status: :created, location: @carrier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriers/1 or /carriers/1.json
  def update
    respond_to do |format|
      if @carrier.update(carrier_params)
        format.html { redirect_to carrier_url(@carrier), notice: "Carrier was successfully updated." }
        format.json { render :show, status: :ok, location: @carrier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1 or /carriers/1.json
  def destroy
    @carrier.destroy

    respond_to do |format|
      format.html { redirect_to carriers_url, notice: "Carrier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrier
      @carrier = Carrier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carrier_params
      params.require(:carrier).permit(:name, :mc_number, :dot_number, :address, :main_contact, :contact_number)
    end



  end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/views/carriers/_carrier.html.erb
<div id="<%= dom_id carrier %>">


<div class="jumbotron">
  <h1> <%= carrier.name %>   </h1>
  <p class="lead">

      
      <%= carrier.address %>
         


  </p>
  <hr class ="my-4">
<p>



</p>
</div>
  

  <p>
    <strong>Mc number:</strong>
    <%= carrier.mc_number %>
  </p>

  <p>
    <strong>Dot number:</strong>
    <%= carrier.dot_number %>
  </p>

    <strong>Main contact:</strong>
    <%= carrier.main_contact %>
  </p>

  <p>
    <strong>Contact number:</strong>
    <%= carrier.contact_number %>
  </p>    
  
</div>

app/views/carriers/_form.html.erb
<%= form_with(model: carrier) do |form| %>
  <% if carrier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carrier.errors.count, "error") %> prohibited this carrier from being saved:</h2>

      <ul>
        <% carrier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div class="form-group">
    <br>
    <%= form.text_field :name ,class:"form-control",placeholder:"Name" %>
  </div>

  <div class="form-group">
    <br>
    <%= form.number_field :mc_number ,class:"form-control",placeholder:"MC Number"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.number_field :dot_number ,class:"form-control",placeholder:"DOT Number" %>
  </div>

  <div class="form-group">
    <br>
    <%= form.text_field :address ,class:"form-control",placeholder:"Address"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.text_field :main_contact ,class:"form-control",placeholder:"Main Contact"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.number_field :contact_number ,class:"form-control",placeholder:"Contact Number" %>
  </div>

  <div>
  <br>
  <button type="submit" class="btn btn-success">Create Carrier</button>
  </div>

<% end %>

app/views/carriers/edit.html.erb
<h1>Edit carrier</h1>

<%= render "form", carrier: @carrier %>

<br>

<div>
  <%= link_to "Show this carrier", @carrier ,class:"btn btn-dark" %> |
  <%= link_to "Back to carriers", carriers_path ,class:"btn btn-dark" %>
</div>

app/views/carriers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carriers</h1>

<%= search_form_for @q do|f| %>
<%= f.label "Search Carrier" %>

<%= f.search_field :name_or_main_contact %>

<%= f.submit  %>

<br>
<br>

<% end %> 
               

<table class="table-dark table table-striped table-bordered table-hover">
  <thead class ="thead-dark">
     <tr>
      
      <th>Name</th>
      <th>Mc Number</th>
      <th>DOT Number</th>
      <th>Address</th>
      <th>Main Contact</th>
      <th> Contact Number </th>
      <th colspan="2"></th>
    </tr>
  
  </thead>
  <tbody>
    <% @carriers.each do |carrier| %>
    <tr>
    <td><%=carrier.name %></td>
    <td><%=carrier.mc_number %></td>
    <td><%=carrier.dot_number %></td>
    <td><%=carrier.address %></td>
    <td><%=carrier.main_contact %></td>
    <td><%=carrier.contact_number %></td>
    <td> <%= link_to "Details", carrier %> </td>

   </tr>
  <% end %>

  </tbody>
</table>

<br>

 <%= link_to "New carrier", new_carrier_path, class:"btn btn-dark" %>
 <!--button type ="button" class="btn btn-secondary">Secondary </button-->
 <p>


                

app/views/carriers/new.html.erb
<br>
<h1>New Carrier</h1>

<%= render "form", carrier: @carrier %>



<div>
  <%= link_to "Back to carriers", carriers_path %>
</div>
<div class="container d-flex align-items-center flex-column">
                
</div>

app/views/carriers/show.html.erb
<p style="color: green"><%= notice %></p>




<%= render @carrier %>

<div>
 <p> 
 <%= link_to "Edit this Carrier", edit_carrier_path(@carrier),class:"btn btn-dark" %> |
 <%= link_to "Back to carriers", carriers_path, class:"btn btn-dark"%>
  <p>   
  <%=link_to "Delete this carrier", @carrier, method: :delete,class:"btn btn-danger"%>
   

</div>