config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'users/update'
  
  get 'users/destroy'
  get 'users/index'
  get 'users/show'
  get 'loads/index'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :kaderes
  resources :carriers
  resources :loads
  resources :users
  get 'home/index'
  get 'home/index2'
  get 'home/about'
  get 'home/login'

  get '/search',to: "home#search"

   
  

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authorize_admin
  def index
   
  end
    
  def index2

  end

  def about

  end
  
  def login

  end

  def authorize_admin
    if current_user&.admin?
     
    end
  end  
  
    
end

app/helpers/home_helper.rb
module HomeHelper
###Trial code

def resource_name
    :user
    end
    
    def resource
    @resource ||= User.new
    end
    
    def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
    end

#End Trial Code
end

app/views/home/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2023 Ogur Software, Inc</p>

    
  </footer>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-uppercase fixed-top" id="mainNav">
            <div class="container">
                
                        
                     
                
                <a class="navbar-brand" href="#page-top">Carrier </a>



                      <li><a href="http://127.0.0.1:3000/home/index2"> Home2</li> 


                
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Home", root_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>                        
                        
                        <%if user_signed_in?%>
                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Carriers",carriers_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Kaderes", kaderes_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Loads", loads_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                            <% if current_user&.role =="admin"%>
                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Users", users_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                            <%end%>

                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Log Out", destroy_user_session_path,method: :delete,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                                <%if current_page?(root_path) %>
                                         <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Edit Profile", edit_user_registration_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                                 <%end%>        

                        <%else%>
                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Login", new_user_session_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                            <li class="nav-item mx-0 mx-lg-1"> <%=link_to "Sign Up", new_user_registration_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>
                        <%end%>    

                       <li class="nav-item mx-0 mx-lg-1"> <%=link_to "About", home_about_path,class:"nav-link py-3 px-0 px-lg-3 rounded "%></li>

                    </ul>
                </div>
               
              

           </div>
    
</nav>

app/views/home/_portfolio.html.erb
<section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Portfolio</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center">
                    <!-- Portfolio Item 1-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal1">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/img/portfolio/cabin.png" alt="cabin" />
                        </div>
                    </div>
                    <!-- Portfolio Item 2-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal2">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/img/portfolio/cake.png" alt="cake" />
                        </div>
                    </div>
                    <!-- Portfolio Item 3-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal3">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="img/portfolio/circus.png" alt="circus" />
                        </div>
                    </div>
                    <!-- Portfolio Item 4-->
                    <div class="col-md-6 col-lg-4 mb-5 mb-lg-0">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal4">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/img/portfolio/game.png" alt="game" />
                        </div>
                    </div>
                    <!-- Portfolio Item 5-->
                    <div class="col-md-6 col-lg-4 mb-5 mb-md-0">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal5">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/img/portfolio/safe.png" alt="safe" />
                        </div>
                    </div>
                    <!-- Portfolio Item 6-->
                    <div class="col-md-6 col-lg-4">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal6">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/image/img/portfolio/submarine.png" alt="submarine" />
                        </div>
                    </div>
                </div>
            </div>
        </section>

app/views/home/about.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>About Us</title>

    </head>
    <body>

    <header class="masthead bg-secondary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
               
                <h1 class="masthead-heading text-uppercase mb-0">About Us</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">Ruby On Rails BackEnd Development</p>
            </div>
        </header>



    <section class="page-section portfolio" id="portfolio">
            <div class="container">
                
                <div class="divider-custom">
                    <p> We Software company currently learning about Ruby On Rails to use it to build powerful apps</p>
                </div>
                
            </div>
        </section>

    </body>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Ogur Software" />
        <title>Carrier Home </title>

    </head> 
    <body>


<%if user_signed_in?%>
<br>
<h1>Home</h1>
<br>
<br>


<div class="container text-center">
  <div class="row row-cols-auto">
    <div class="col"><li>  <i class="bi bi-buildings"></i>  <%= link_to "Carriers",carriers_path%></li></div>
    <div class="col"><li> <i class="bi bi-people"></i> <%= link_to "Kaderes",kaderes_path%></li></div>
    <div class="col"><li><i class="bi bi-box-seam"></i> <%= link_to "Loads",loads_path%></li></div>
    <div class="col">Fleet (under construction)</div>
    <div class="col"><li><i class="bi bi-box-seam"></i> <%= link_to "Users(test)",users_path%></li></div>
   
     
  </div>
  
</div>



<%else%>
<br>
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>



   

  <div><%= f.submit "Login" %></div>

  
<% end %>

<%= render "devise/shared/links" %>

<%end%> 

</body>

app/views/home/login.html.erb
  <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Signin Template · Bootstrap v5.2</title>
  
  
  
   <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p>
  </form>
</main>


    
  </body>
</html>

app/views/home/search.html.erb
<h1> Search </h1>

<table class="table-dark table table-striped table-bordered table-hover">
  <thead class ="thead-dark">
     <tr>
      <th>Name</th>
    </tr> 
  </thead>
  <tbody>
  <% @results.each do |carrier| %>
    <tr>
        <td><%= carrier.name%></td>
    </tr>

    <%end%> 
  </tbody>  
</table>