config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'users/update'
  
  get 'users/destroy'
  get 'users/index'
  get 'users/show'
  get 'loads/index'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :kaderes
  resources :carriers
  resources :loads
  resources :users
  get 'home/index'
  get 'home/index2'
  get 'home/about'
  get 'home/login'

  get '/search',to: "home#search"

   
  

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/load.rb
class Load < ApplicationRecord
    has_one_attached :rate_confirmation
    belongs_to :kadere, optional:true
   enum status: {preplan:0,dispatched:1,at_shipper:2,is_loaded:3,at_receiver:4,empty:5 } 
   # enum status: [:preplan,:dispatched,:at_shipper,:is_loaded,:at_receiver,:empty] 

end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :set_load, only: %i[ show edit update destroy ]
  include ActiveStorage::SetCurrent


  # GET /loads or /loads.json

  
  def index
   
    @loads = Load.all
    @q =Load.ransack(params[:q])
    @loads = @q.result
  end



  # GET /loads/1 or /loads/1.json
  def show
  end

  # GET /loads/new
  def new
    @load = Load.new
  end

  # GET /loads/1/edit
  def edit
  end

  # POST /loads or /loads.json
  def create
    @load = Load.new(load_params)

    respond_to do |format|
      if @load.save
        format.html { redirect_to load_url(@load), notice: "Load was successfully created." }
        format.json { render :show, status: :created, location: @load }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loads/1 or /loads/1.json
  def update
    respond_to do |format|
      if @load.update(load_params)
        format.html { redirect_to load_url(@load), notice: "load was successfully updated." }
        format.json { render :show, status: :ok, location: @load }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loads/1 or /loads/1.json
  def destroy
    @load.destroy

    respond_to do |format|
      format.html { redirect_to loads_url, notice: "load was successfully deleted." }
      format.json { head :no_content }
    end
  end
 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load
      @load = Load.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def load_params
  
    
    params.require(:load).permit(:load_number, :pickup_city, :delivery_city, :broker, :rate, :pickup_date , :delivery_date ,:rate_confirmation, :kadere_id,:status)
    end
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/views/loads/_form.html.erb
<%= form_with(model: load) do |form| %>
  <% if load.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(load.errors.count, "error") %> prohibited this load from being saved:</h2>

      <ul>
        <% load.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">

  <div class="form-group">
    <br>
    <%= form.text_field :load_number ,class:"form-control",placeholder:"Load Number" %>
  </div>

  <div>
  <br>  
  <select class="form-control", name="load[kadere_id]">
    <% Kadere.all.each do |kadere| %>
        <option value="<%= kadere.id %>"><%= kadere.name %></option>
    <% end %>
  </select>
  </div>

  <div class="form-group">
    <br>
    <%= form.text_field :pickup_city ,class:"form-control",placeholder:"Pickup City"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.text_field :delivery_city ,class:"form-control",placeholder:"Delivery City"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.text_field :broker,class:"form-control",placeholder:"Broker"%>
    <br>
  </div>

  <div class="input-group mb-3">
   
    <span class="input-group-text">$</span>
     <%= form.number_field :rate ,class:"form-control",placeholder:"Rate"%>
     
  </div>

   <div class="form-group">
    <br>
    <%= form.datetime_local_field :pickup_date ,class:"form-control",placeholder:"Pickup Date"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.datetime_local_field :delivery_date ,class:"form-control",placeholder:"Delivery Date"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.file_field :rate_confirmation ,class:"form-control",placeholder:"Rate Confirmation"%>
  </div>

  
  

  <div class="form-group">
    <br>
    <%= form.label :status%>
        <%= form.select :status, options_for_select(Load.statuses.map {|key, value| [key.titleize, Load.statuses.key(value)]}, @load.status),class:"form-control" %>



 <div> 
 <br>
<button type="submit" class="btn btn-success">Create Load</button> |  <%= link_to "Back to loads", loads_path,class:"btn btn-dark" %>


  </div>
<% end %>

app/views/loads/_load.html.erb
<div id="<%= dom_id load %>">
 <div class="jumbotron">

    <h1>Load Number# <%= load.load_number %> <h1>

    <hr class ="my-4">
    
      </p>


  </div>
  <p>
    <strong>Kadere:</strong>
    <%= load.kadere.name if load.kadere%>
  </p>

  <p>
    <strong>Pickup City:</strong>
    <%= load.pickup_city %>
  </p>

  <p>
    <strong>Delivery City:</strong>
    <%= load.delivery_city %>
  </p>

  <p>
    <strong>Broker:</strong>
    <%= load.broker %>
  </p>

  <p>
    <strong>Rate:</strong>
    <%= load.rate %>
  </p>

  <p>
    <strong>Pickup Date:</strong>
    <%= load.pickup_date %>
  </p>

  <p>
    <strong>Delivery Date:</strong>
    <%= load.delivery_date %>
  </p>

  <p>
    <strong>Rate Confirmation:</strong>
    <%= load.rate_confirmation.filename.to_s %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= load.status %>
  </p>

</div>

app/views/loads/edit.html.erb
<h1>Editing Load</h1>

<%= render "form", load: @load %>

<br>

<div>
  <%= link_to "Show this load", @load,class:"btn btn-dark" %> |
  <%= link_to "Back to loads", loads_path,class:"btn btn-dark" %>
</div>

app/views/loads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Loads</h1>


<%= search_form_for @q do|f| %>
<%= f.label "Search Loads" %>

<%= f.search_field :load_number_or_broker %>

<%= f.submit  %>

<br>
<br>

<% end %> 


<table class="table-dark table table-striped table-bordered table-hover">
  <thead class ="thead-dark">
     <tr>
      <th>Load #</th>
      <th>Kadere</th>
      <th>Pickup City</th>
      <th>Delivery City</th>
      <th>Broker</th>
      <th>Rate</th>
      <th>Pickup Date </th>
      <th>Delivery Date </th>
      <th>Rate Confirmation </th>
      <th>Status </th>
      <th colspan="2"></th>
    </tr>
  
  </thead>
  <tbody>
    <% @loads.each do |load| %>
    <tr>
    <td><%=load.load_number %></td>
    <td><%=load&.kadere&.name %></td>
    <td><%=load.pickup_city %></td>
    <td><%=load.delivery_city %></td>
    <td><%=load.broker %></td>
    <td><%=load.rate%></td>
    <td><%=load.pickup_date%></td>
    <td><%=load.delivery_date%></td>
    <td><%=link_to "View Document", load.rate_confirmation.url, download: true %></td>
    <td><%=load.status%></td>
    <td> <%= link_to "Show this Load", load %> </td>

   </tr>
  <% end %>

  </tbody>
</table>




<br>

<%= link_to "New Load", new_load_path, class:"btn btn-dark" %>
<p>
 

app/views/loads/new.html.erb
<h1>New Load</h1>

<%= render "form", load: @load %>

<br>

app/views/loads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @load %>
<%= link_to "Download Rate Confirmation", @load.rate_confirmation.url, download: true %>
<div>
  <p>
  <%= link_to "Edit this Load", edit_load_path(@load), class:"btn btn-dark" %> |  
  <%= link_to "Back to Loads", loads_path , class:"btn btn-dark" %>
  <p>
  <%= button_to "Delete this Load", @load, method: :delete , class:"btn btn-danger" %>
</div>