config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'users/update'
  
  get 'users/destroy'
  get 'users/index'
  get 'users/show'
  get 'loads/index'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :kaderes
  resources :carriers
  resources :loads
  resources :users
  get 'home/index'
  get 'home/index2'
  get 'home/about'
  get 'home/login'

  get '/search',to: "home#search"

   
  

 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/kadere.rb
class Kadere < ApplicationRecord
    belongs_to :carrier,optional: true
    has_many :loads

end

app/controllers/kaderes_controller.rb
class KaderesController < ApplicationController
  before_action :set_kadere, only: %i[ show edit update destroy ]
  

  # GET /kaderes or /kaderes.json

  
  def index
   
    @kaderes = Kadere.all
    @q =Kadere.ransack(params[:q])
    @kaderes = @q.result
  end


  # if params[:search].blank?
   #   redirect_to kaders_path and return
   # else
    #  @parameter =params[:search].downcase
    #  @kadere_results = Kaderes.all.where('name LIKE?',"%#{parameter}%")
   # end
 # end 

  # GET /kaderes/1 or /kaderes/1.json
  def show
  end

  # GET /kaderes/new
  def new
    @kadere = Kadere.new
  end

  # GET /kaderes/1/edit
  def edit
  end

  # POST /kaderes or /kaderes.json
  def create
    @kadere = Kadere.new(kadere_params)

    respond_to do |format|
      if @kadere.save
        format.html { redirect_to kadere_url(@kadere), notice: "Kadere was successfully created." }
        format.json { render :show, status: :created, location: @kadere }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kadere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kaderes/1 or /kaderes/1.json
  def update
    respond_to do |format|
      if @kadere.update(kadere_params)
        format.html { redirect_to kadere_url(@kadere), notice: "Kadere was successfully updated." }
        format.json { render :show, status: :ok, location: @kadere }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kadere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kaderes/1 or /kaderes/1.json
  def destroy
    @kadere.destroy

    respond_to do |format|
      format.html { redirect_to kaderes_url, notice: "Kadere was successfully destroyed." }
      format.json { head :no_content }
    end
  end
 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kadere
      @kadere = Kadere.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kadere_params
      params.require(:kadere).permit(:name, :phone, :email, :truck_number, :trailer_number, :carrier_id)
    end

    
end

app/helpers/kaderes_helper.rb
module KaderesHelper
end

app/views/kaderes/_form.html.erb
<%= form_with(model: kadere) do |form| %>
  <% if kadere.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kadere.errors.count, "error") %> prohibited this kadere from being saved:</h2>

      <ul>
        <% kadere.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="form-group">
    <br>
    <%= form.text_field :name ,class:"form-control",placeholder:"Name" %>
  </div>

  <div class="form-group">
    <br>
    <%= form.number_field :phone ,class:"form-control",placeholder:"Phone Number"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.text_field :email ,class:"form-control",placeholder:"Email"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.number_field :truck_number,class:"form-control",placeholder:"Truck Number"%>
  </div>

  <div class="form-group">
    <br>
    <%= form.number_field :trailer_number ,class:"form-control",placeholder:"Trailer Number"%>
  </div>

 <div>
  <br>  
  <select class="form-control", name="kadere[carrier_id]">
    <% Carrier.all.each do |carrier| %>
        <option value="<%= carrier.id %>"><%= carrier.name %></option>
    <% end %>
  </select>
  </div>

  <div>
  <br>
     <button type="submit" class="btn btn-success">Create Kadere</button>
  </div>
<% end %>

app/views/kaderes/_kadere.html.erb
<div id="<%= dom_id kadere %>">
  <div class="jumbotron">
    
    <h1><%= kadere.name %></h1>

    <hr class ="my-4">
  </div>

  <p>
    <strong>Phone:</strong>
    <%= kadere.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= kadere.email %>
  </p>

  <p>
    <strong>Truck number:</strong>
    <%= kadere.truck_number %>
  </p>

  <p>
    <strong>Trailer number:</strong>
    <%= kadere.trailer_number %>
  </p>

  <p>
    <strong>Carrier company:</strong>
    <%= kadere.carrier.name if kadere.carrier%>
  </p>

</div>

app/views/kaderes/edit.html.erb
<h1>Editing kadere</h1>

<%= render "form", kadere: @kadere %>

<br>

<div>
  <%= link_to "Show this kadere", @kadere, class:"btn btn-dark" %> |
  <%= link_to "Back to kaderes", kaderes_path,class:"btn btn-dark" %>
</div>

app/views/kaderes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Kaderes</h1>

<%= search_form_for @q do|f| %>
<%= f.label "Search Kadere" %>

<%= f.search_field :name_or_email_cont %>

<%= f.submit  %>
<br>
<br>

<% end %> 

<table class="table-dark table table-striped table-bordered table-hover">
  <thead class ="thead-dark">
     <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Truck Number</th>
      <th>Trailer Number</th>
      <th>Carrier Company </th>
      <th colspan="2"></th>
    </tr>
  
  </thead>
  <tbody>
    <% @kaderes.each do |kadere| %>
    <tr>
    <td><%=kadere.name %></td>
    <td><%=kadere.phone %></td>
    <td><%=kadere.email %></td>
    <td><%=kadere.truck_number %></td>
    <td><%=kadere.trailer_number%></td>
    <td><%=kadere&.carrier&.name %></td>
    <td> <%= link_to "Show this Kadere", kadere %> </td>

   </tr>
  <% end %>

  </tbody>
</table>




<br>

<%= link_to "New kadere", new_kadere_path, class:"btn btn-dark" %>
<p>
 

app/views/kaderes/new.html.erb
<h1>New kadere</h1>

<%= render "form", kadere: @kadere %>

<br>

<div>
  <%= link_to "Back to kaderes", kaderes_path %>
</div>

app/views/kaderes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kadere %>

<div>
  <%= link_to "Edit this kadere", edit_kadere_path(@kadere),  class:"btn btn-dark" %> |
  <%= link_to "Back to kaderes", kaderes_path, class:"btn btn-dark" %>
<p>
  <%= button_to "Destroy this kadere", @kadere, method: :delete, class:"btn btn-danger" %>
</div>